In [15]:
# 创建一个整形值列表
L = list(range(10))
print(L)
print(type(L))

# 创建一个字符串列表
L2 = [str(c) for c in L]
print(L2)
print(type(L2))

L3 = [True, '2', 3.0, 4]
[type(item) for item in L3]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
<class 'list'>


[bool, str, float, int]

In [16]:
# python中创建固定类型数组
import array
L = list(range(10))
A = array.array('i', L)  # 这里的'i'是一个数据类型码，表示数据为整形
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# 更实用的是numpy中的ndarray对象
import numpy as np

# 整型数组
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [19]:
# 不同于python列表，numpy要求数组必须包含同一类型的数据，若不匹配则向上转换（如果可行）
np.array([3.14, 4, 2, 3])  # 这里整型被转换为浮点型

array([3.14, 4.  , 2.  , 3.  ])

In [20]:
# 若希望明确设置数组的数据类型，可用dtype关键字
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [25]:
# 不同于python列表，numpy数组可以被指定为多维的
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [45]:
# 面对大型数组时，使用从头创建数组

# 创建一个长度为10的数组，数组的值都是0
a = np.zeros(10, dtype=int)
print(a)

# 创建一个3×5的浮点型数组，数组的值都是1
b = np.ones((3, 5), dtype=float)
print(b)

# 创建一个3×5的浮点型数组，数组的值是一个线性序列，从0开始，到20结束，步长为2（它和内置的range函数类似）
c = np.arange(0, 20, 2)
print(c)

# 创建一个5个元素的数组，且5个数均匀地分配0~1
d = np.linspace(0, 1, 5)
print(d)

# 创建一个3×3的，在0~1均匀分布的随机数组成的数组
e = np.random.random((3, 3))
print(e)

# 创建一个3×3的，均值为0，方差为1的正态分布随机数数组
f = np.random.normal(0, 1, (3, 3))
print(f)

# 创建一个3×3的，[0, 10)区间的随机整型数组
g = np.random.randint(0, 10, (3, 3))
print(g)

# 创建一个3×3的单位矩阵
h = np.eye(3)
print(h)

#创建一个由3个整型数组成的未初始化的数组，数组的值是内存空间中的任意值
i = np.empty(3)
print(i)

[0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[ 0  2  4  6  8 10 12 14 16 18]
[0.   0.25 0.5  0.75 1.  ]
[[0.48819925 0.61494248 0.87290719]
 [0.83267985 0.55101986 0.17799115]
 [0.6161209  0.39513221 0.88458536]]
[[-0.90265637  3.63760035 -0.8271786 ]
 [ 0.28143104 -0.18270028 -1.18983161]
 [-1.46283028  1.63360508  0.77964155]]
[[3 6 4]
 [4 9 7]
 [4 5 0]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1. 1. 1.]
